In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 학습 모델 저장을 위한 라이브러리
import pickle

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# 가져올 모델 경로
best_model_path = '/content/drive/MyDrive/xgboost_pca.dat'
# 예측할 파일 경로
prediction_path = '/content/drive/MyDrive/test_pca.csv'

In [4]:
with open(best_model_path, 'rb') as fp :
    model1 = pickle.load(fp)
    encoder1 = pickle.load(fp)
    scaler1 = pickle.load(fp)

display(model1)
display(encoder1)
display(scaler1)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

LabelEncoder()

StandardScaler()

In [5]:
# 예측할 데이터를 읽어온다.
df1 = pd.read_csv(prediction_path)
df1

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,...,PC15,PC16,PC17,PC18,PC19,PC20,PC21,PC22,PC23,ID
0,1.228792,-0.748490,-0.602236,-1.450564,-0.552362,2.679309,-0.408888,-1.858074,0.993738,0.517364,...,0.530005,-0.123493,-0.566897,0.224170,-0.221351,0.248941,0.585357,-0.349229,-0.089840,TEST_00000
1,1.308212,-1.009214,-1.181219,-0.062981,-0.257458,3.896014,-0.193046,1.904872,-0.122020,0.419752,...,0.360378,1.720758,-0.950310,0.163255,0.860265,0.376284,0.133427,0.917363,0.538964,TEST_00001
2,3.047477,-3.756945,0.231777,-1.927104,-0.828993,1.212076,-0.000663,0.660699,0.309538,-1.564406,...,-0.082507,1.123932,-0.723907,0.651698,-0.337620,1.146165,-0.473117,-0.256689,-0.406865,TEST_00002
3,-2.200002,-0.067853,5.993718,1.389701,0.108854,0.342497,0.301390,-0.330712,-0.728262,-0.968435,...,-0.207753,-0.207505,-0.502691,-0.225574,0.401501,0.053114,0.399852,-0.419079,0.052597,TEST_00003
4,-2.016930,-0.720372,3.217356,3.038069,0.088245,0.305889,0.332487,0.569560,-0.270748,-1.416359,...,3.881476,1.435988,0.814887,-0.708649,0.544349,-1.056559,-0.225426,0.297014,-1.528734,TEST_00004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,-3.570285,0.774886,-1.145774,-1.543501,-0.138328,-0.670257,2.507237,-0.150657,0.117823,-0.111879,...,-0.000129,0.024214,0.032119,0.050842,0.122008,-0.048845,0.087446,0.028667,-0.016839,TEST_99995
99996,-3.197031,0.561615,-0.932626,-1.334345,0.030509,-0.898282,-2.510813,0.223855,-1.360074,0.983665,...,-0.746358,1.452156,0.444910,0.307407,0.368590,-0.155195,-0.182673,0.390617,0.141633,TEST_99996
99997,-3.599583,0.753901,-1.203662,-1.510599,-0.047048,-0.585681,2.542838,-0.181542,-0.493915,0.234250,...,0.011262,-0.064031,-0.260000,0.336547,-0.090959,-0.067602,-0.031468,-0.022439,-0.029871,TEST_99997
99998,19.175221,4.790582,0.031932,1.107363,-1.777221,-2.428584,0.255555,-4.682717,-4.443229,0.040147,...,0.446560,-1.184863,-2.077295,0.042314,1.383913,-0.978685,1.065079,-3.096785,-1.172506,TEST_99998
99999,-3.492373,0.623295,-0.849643,-1.493503,-0.222058,-1.199035,-2.495225,0.365069,-0.159182,-0.105648,...,-0.110330,0.250451,-0.319429,0.638581,-0.094638,-0.065225,-0.072716,0.081471,0.022656,TEST_99999

In [6]:
train_df = pd.read_csv("/content/drive/MyDrive/train_pca.csv")
# feature_columns = train_df.drop(columns=['ID', 'Segment', '기준년월']).columns.tolist() wide에는 기준년월 없음
feature_columns = train_df.drop(columns=['ID', 'Segment']).columns.tolist()


# 1. ID, 기준년월 제거
#X_pred = df1.drop(columns=['ID', '기준년월'])
X_pred = df1.drop(columns=['ID'])

# 2. object형 컬럼 라벨 인코딩 (주의: fit_transform은 임시방편임)
for col in X_pred.select_dtypes(include='object').columns:
    le = LabelEncoder()
    X_pred[col] = le.fit_transform(X_pred[col].astype(str))

# 3. 학습 데이터와 동일한 컬럼 순서로 정렬
X_pred = X_pred[feature_columns]

In [7]:
# 표준화 적용
X_pred_scaled = scaler1.transform(X_pred)
X_pred_scaled

array([[ 0.29720143, -0.27675603, -0.26532226, ...,  0.89588313,
        -0.55614785, -0.14462972],
       [ 0.31641036, -0.37315943, -0.52039974, ...,  0.20420905,
         1.4609035 ,  0.86765754],
       [ 0.73707742, -1.38913937,  0.102112  , ..., -0.72410189,
        -0.40877863, -0.65499587],
       ...,
       [-0.87061231,  0.27875677, -0.53028722, ..., -0.04816224,
        -0.03573386, -0.04808747],
       [ 4.63781089,  1.77132929,  0.01406805, ...,  1.63009347,
        -4.93163805, -1.88757144],
       [-0.84468202,  0.23046475, -0.37432006, ..., -0.11129101,
         0.12974317,  0.03647251]])

In [8]:
# 예측
pred = model1.predict(X_pred_scaled)
pred_labels = encoder1.inverse_transform(pred)

In [9]:
# 결과 저장
df_result = pd.DataFrame({
    'ID': df1['ID'],
    'Segment': pred_labels
})

df_result.to_csv('/content/drive/MyDrive/submission_xgboost_pca.csv', index=False)
print("제출 파일 저장 완료")

제출 파일 저장 완료

In [ ]:
df1 = pd.read_csv("/content/drive/MyDrive/submission.csv")
df1

                ID Segment
0       TEST_00000       D
1       TEST_00001       E
2       TEST_00002       C
3       TEST_00003       E
4       TEST_00004       E
...            ...     ...
599995  TEST_99995       E
599996  TEST_99996       E
599997  TEST_99997       E
599998  TEST_99998       D
599999  TEST_99999       E

[600000 rows x 2 columns]

In [ ]:
# 중복된 ID만 추출
duplicated_ids = df1[df1['ID'].duplicated(keep=False)]
print(duplicated_ids)

                ID Segment
0       TEST_00000       D
1       TEST_00001       E
2       TEST_00002       C
3       TEST_00003       E
4       TEST_00004       E
...            ...     ...
599995  TEST_99995       E
599996  TEST_99996       E
599997  TEST_99997       E
599998  TEST_99998       D
599999  TEST_99999       E

[600000 rows x 2 columns]

In [ ]:
print("전체 행 수:", len(df1))
print("ID의 유니크 수:", df1['ID'].nunique())

전체 행 수: 600000
ID의 유니크 수: 100000

True